import { PixelRatio } from "react-native"

export const fontSizes = {
  fs10: 10 / PixelRatio.getFontScale(),
  fs11: 11 / PixelRatio.getFontScale(),
  fs12: 12 / PixelRatio.getFontScale(),
  fs13: 13 / PixelRatio.getFontScale(),
  fs14: 14 / PixelRatio.getFontScale(),
  fs15: 15 / PixelRatio.getFontScale(),
  fs16: 16 / PixelRatio.getFontScale(),
  fs18: 18 / PixelRatio.getFontScale(),
  fs19: 19 / PixelRatio.getFontScale(),
  fs20: 20 / PixelRatio.getFontScale(),
  fs21: 21 / PixelRatio.getFontScale(),
  fs22: 22 / PixelRatio.getFontScale(),
  fs23: 23 / PixelRatio.getFontScale(),
  fs24: 24 / PixelRatio.getFontScale(),
  fs25: 25 / PixelRatio.getFontScale(),
  fs26: 26 / PixelRatio.getFontScale(),
  fs28: 28 / PixelRatio.getFontScale(),
  fs29: 29 / PixelRatio.getFontScale(),
  fs30: 30 / PixelRatio.getFontScale(),
  fs31: 31 / PixelRatio.getFontScale(),
  fs32: 32 / PixelRatio.getFontScale(),
  fs33: 33 / PixelRatio.getFontScale(),
  fs34: 34 / PixelRatio.getFontScale(),
  fs35: 35 / PixelRatio.getFontScale(),
  fs36: 36 / PixelRatio.getFontScale(),
  fs37: 37 / PixelRatio.getFontScale(),
  fs38: 38 / PixelRatio.getFontScale(),
  fs39: 39 / PixelRatio.getFontScale(),
  fs40: 40 / PixelRatio.getFontScale(),
  fs41: 41 / PixelRatio.getFontScale(),
  fs42: 42 / PixelRatio.getFontScale(),
  fs43: 43 / PixelRatio.getFontScale(),
  fs44: 44 / PixelRatio.getFontScale(),
  fs45: 45 / PixelRatio.getFontScale(),
  fs46: 46 / PixelRatio.getFontScale(),
  fs47: 47 / PixelRatio.getFontScale(),
  fs48: 48 / PixelRatio.getFontScale(),
  fs49: 49 / PixelRatio.getFontScale(),
  fs50: 50 / PixelRatio.getFontScale(),
} as const
