import { Translations } from "./en"

const ar: Translations = {
  common: {
    ok: "موافق",
    cancel: "إلغاء",
    back: "رجوع",
    save: "حفظ",
    delete: "حذف",
    loading: "جاري التحميل...",
    error: "خطأ",
    retry: "إعادة المحاولة",
    search: "بحث",
    call: "اتصال",
    whatsapp: "واتساب",
    location: "الموقع",
    negotiable: "قابل للتفاوض",
    fixed: "سعر ثابت",
    active: "نشط",
    paused: "متوقف",
    sold: "مباع",
    edit: "تعديل",
    next: "التالي",
    confirm: "تأكيد",
    favorites: "المفضلة",
    currency: "درهم",
    new: "جديد",
    all: "الكل",
    farmer: "فلاح",
    seller: "البائع",
    whatsappMessage: "السلام عليكم، أود الاستفسار عن إعلانك: ",
    verificationFailed: "رمز التأكيد غير صحيح",
    incompleteCode: "يرجى إدخال الرمز المكون من 6 أرقام",
    warning: "تنبيه",
    notSpecified: "غير محدد",
    noFavorites: "لا توجد إعلانات في المفضلة بعد",
    noFavoritesDesc: "تصفح الإعلانات وانقر على رمز القلوب لحفظ المنتجات هنا.",
    today: "اليوم",
    yesterday: "أمس",
    daysAgo: "أيام مضت",
    days: "أيام",
    views: "مشاهدة",
    hoursUnit: "ساعة",
    noResults: "لم يتم العثور على نتائج",
  },
  welcome: {
    title: "مرحباً بك في سوق الفلاح",
    subtitle: "سجل معنا لتبدأ بيع وشراء منتجاتك الفلاحية بكل سهولة.",
    getStarted: "ابدأ الآن",
    login: "تسجيل الدخول",
  },
  login: {
    title: "تسجيل الدخول",
    phone: "رقم الهاتف",
    phonePlaceholder: "06 XX XX XX XX",
    password: "كلمة المرور",
    passwordPlaceholder: "••••••••",
    forgotPassword: "نسيت كلمة المرور؟",
    submit: "تسجيل الدخول",
    noAccount: "ليس لديك حساب؟",
    registerNow: "سجل الآن",
    phoneRequired: "رقم الهاتف مطلوب",
    phoneInvalid: "رقم الهاتف غير صحيح",
    passwordRequired: "كلمة السر مطلوبة",
    passwordMinLength: "يجب أن تتكون كلمة السر من 6 أحرف على الأقل",
    loginFailedTitle: "فشل تسجيل الدخول",
    loginFailedMsg: "رقم الهاتف أو كلمة السر غير صحيحة",
  },
  register: {
    title: "فتح حساب جديد",
    fullName: "الاسم الكامل",
    fullNamePlaceholder: "مثال: أحمد العلمي",
    phone: "رقم الهاتف",
    phonePlaceholder: "06XXXXXXXX",
    password: "كلمة المرور",
    passwordPlaceholder: "••••••••",
    submit: "فتح حساب جديد",
    hasAccount: "لديك حساب بالفعل؟",
    loginNow: "سجل الدخول",
    nameRequired: "الاسم الكامل مطلوب",
    addressRequired: "العنوان مطلوب لتحديد موقع السلع",
    registerFailedTitle: "فشل التسجيل",
    registerFailedMsg: "حدث خطأ أثناء فتح الحساب",
  },
  verifyPhone: {
    title: "تأكيد رقم الهاتف",
    subtitle: "أدخل الرمز الذي أرسلناه في رسالة نصية (SMS) للرقم",
    submit: "تأكيد",
    resend: "لم تستلم الرمز؟ أعد الإرسال",
  },
  home: {
    title: "سوق الفلاح",
    searchPlaceholder: "ابحث عن منتج...",
    categoriesTitle: "ماذا تبحث عن؟",
    recentTitle: "آخر الإعلانات",
    viewAll: "عرض الكل",
    categories: {
      produce: "خضر وفواكه",
      machinery: "آليات ومعدات",
      livestock: "مواشي",
      fertilizers: "أسمدة",
      seeds: "بذور",
    },
  },
  search: {
    title: "البحث",
    inputPlaceholder: "عن ماذا تبحث؟ (مثال: جرار، طماطم)",
    selectCity: "اختر المدينة",
    categoriesSection: "الأصناف",
    allCategories: "الكل",
    priceRange: "السعر (درهم)",
    priceFrom: "من",
    priceTo: "إلى",
    resultsCount: "نتائج البحث",
    sortBy: "ترتيب",
  },
  addListing: {
    title: "إضافة إعلان جديد",
    step1Title: "ماذا تريد أن تبيع؟",
    produceCategory: "منتجات فلاحية",
    equipmentCategory: "آليات ومعدات",
    step2Title: "إضافة صور",
    photoLimit: "5 صور كحد أقصى",
    uploadPlaceholder: "اضغط هنا لاختيار الصور",
    listingTitleLabel: "عنوان الإعلان",
    listingTitlePlaceholder: "مثال: بصل ممتاز للبيع أو جرار في حالة جيدة",
    listingTitleHelper: "العنوان يساعد المشترين في العثور على إعلانك بسرعة",
    priceLabel: "السعر (درهم)",
    pricePlaceholder: "0.00",
    quantityLabel: "الكمية",
    quantityPlaceholder: "مثال: 100",
    unitLabel: "وحدة القياس",
    addressLabel: "العنوان",
    addressPlaceholder: "مثال: سيدي بنور، الدكالة",
    listingDirectionLabel: "نوع الإعلان",
    directionSell: "عرض بيع",
    directionBuy: "طلب شراء",
    listingPurposeLabel: "غرض الإعلان",
    purposeSell: "بيع",
    purposeRent: "كراء",
    priceTypeLabel: "نوع الثمن",
    priceTypeFixed: "ثمن ثابت",
    priceTypeNegotiable: "ثمن قابل للتفاوض",
    priceTypeContact: "الاتصال للاتفاق",
    conditionLabel: "حالة المعدات",
    conditionNew: "جديد",
    conditionUsed: "مستعمل",
    titleRequired: "عنوان الإعلان مطلوب",
    priceRequired: "الثمن مطلوب",
    quantityRequired: "الكمية مطلوبة",
    addressRequired: "العنوان مطلوب",
    descriptionMinLength: "الوصف خاص يكون فيه على الأقل 10 د الحروف",
    photoLimitErrorTitle: "الحد الأقصى للصور",
    photoLimitErrorMsg: "يمكنك إضافة 5 صور كحد أقصى",
    permissionDeniedTitle: "إذن مرفوض",
    permissionDeniedMsg: "يجب السماح بالوصول إلى ألبوم الصور لاختيار صورة.",
    cameraPermissionDeniedTitle: "تم رفض إذن الكاميرا",
    cameraPermissionDeniedMsg: "مطلوب الوصول إلى الكاميرا لالتقاط صور لعناصرك.",
    addPhotoSourceTitle: "إضافة صورة",
    cameraOption: "التقاط صورة",
    galleryOption: "اختيار من المعرض",
    cancelOption: "إلغاء",
    uploadErrorTitle: "فشل رفع الصورة",
    uploadErrorMsg: "حدث خطأ أثناء تحميل الصورة.",
    missingInfoTitle: "معلومات ناقصة",
    missingInfoMsg: "يرجى ملء جميع الحقول الضرورية",
    descriptionShortTitle: "الوصف قصير جداً",
    descriptionShortMsg: "الوصف خاص يكون فيه على الأقل 10 د الحروف",
    noDescription: "لا يوجد وصف حالياً",
    successTitle: "تم بنجاح",
    successMsg: "تم نشر إعلانك بنجاح على سوق الفلاح",
    successOk: "موافق",
    publishErrorTitle: "فشل نشر الإعلان",
    publishErrorDefault: "حدث خطأ أثناء نشر الإعلان",
    descriptionPlaceholder: "وصف حالة السلعة، الجودة، الموديل، إلخ.",
    descriptionLabel: "معلومات إضافية",
    modelPlaceholder: "مثال: 2018",
    modelLabel: "الموديل (السنة)",
    hoursPlaceholder: "مثال: 1200",
    hoursLabel: "عدد الساعات",
    regionLabel: "الجهة",
    selectRegionPlaceholder: "اختر الجهة",
    regionWarningTitle: "تنبيه",
    regionWarningMsg: "عافاك اختر الجهة أولاً",
    provinceLabel: "الإقليم",
    selectProvincePlaceholder: "اختر الإقليم",
    submit: "نشر الإعلان",
    categoryRequired: "القسم مطلوب",
    productTypeRequired: "نوع المنتج مطلوب",
    unitRequired: "وحدة القياس مطلوبة",
    selectCategoryPlaceholder: "اختر القسم",
    selectProductTypePlaceholder: "اختر نوع المنتج",
    selectUnitPlaceholder: "اختر وحدة القياس",
  },
  editListing: {
    title: "تعديل الإعلان",
    saveBtn: "حفظ التغييرات",
  },
  myListings: {
    title: "إعلاناتي",
    stats: {
      total: "المجموع",
      views: "المشاهدات",
      messages: "الرسائل",
    },
    tabs: {
      active: "نشطة",
      paused: "متوقفة",
      sold: "مباعة",
    },
    noListings: "ليس لديك أي إعلانات في هذا القسم.",
    logoutTitle: "تسجيل الخروج",
    logoutConfirm: "هل أنت متأكد من رغبتك في تسجيل الخروج؟",
    logoutAction: "خروج",
    deleteTitle: "حذف الإعلان",
    deleteNotSupported: "الحذف غير مدعوم حالياً في السيرفر.",
    markSoldSuccess: "بصحتك! تم تغيير حالة الإعلان إلى مباع.",
    updateSuccess: "تم تحديث إعلانك بنجاح!",
  },
  listingDetails: {
    title: "تفاصيل الإعلان",
    memberSince: "عضو منذ",
    productInfo: "معلومات المنتج",
    specs: {
      model: "الموديل",
      hours: "ساعات العمل",
      quantity: "الكمية المتوفرة",
      unit: "الوحدة",
    },
    report: {
      title: "الإبلاغ عن الإعلان",
      button: "الإبلاغ عن هذا الإعلان",
      reasonLabel: "سبب الإبلاغ",
      descriptionPlaceholder: "تقديم المزيد من التفاصيل (اختياري)...",
      submit: "إرسال البلاغ",
      cancel: "إلغاء",
      successTitle: "تم إرسال البلاغ",
      successMsg: "شكراً لك. لقد تلقينا بلاغك وسنقوم بمراجعة هذا الإعلان قريباً.",
      errorTitle: "خطأ",
      errorMsg: "تعذر إرسال البلاغ. يرجى المحاولة مرة أخرى لاحقاً.",
      reasons: {
        scam: "احتيال أو نصب",
        spam: "مكرر أو غير مرغوب فيه",
        incorrect: "تفاصيل أو سعر غير صحيح",
        offensive: "محتوى غير لائق أو مسيء",
        other: "سبب آخر",
      },
    },
  },
  guest: {
    continueAsGuest: "الاستمرار كزائر",
    loginRegisterCta: "تسجيل الدخول / إنشاء حساب",
    addListingTitle: "سجل الدخول لإضافة إعلان",
    addListingDesc:
      "لتتمكن من إضافة إعلاناتك ومنتجاتك والتواصل مع المزارعين الآخرين، يجب عليك تسجيل الدخول أولاً.",
    favoritesTitle: "سجل الدخول لعرض المفضلة",
    favoritesDesc:
      "لتتمكن من حفظ إعلاناتك ومنتجاتك المفضلة والرجوع إليها في أي وقت، يجب عليك تسجيل الدخول.",
    myListingsTitle: "سجل الدخول لعرض حسابك",
    myListingsDesc: "لتتمكن من عرض إعلاناتك، مشاهداتك، وإدارة حسابك، يجب عليك تسجيل الدخول أولاً.",
    contactAlertTitle: "تنبيه",
    contactAlertMsg: "هذا الإجراء يتطلب تسجيل الدخول. هل ترغب في تسجيل الدخول أو إنشاء حساب الآن؟",
    loginCta: "تسجيل الدخول",
  },
  categories: {
    fruits: "فواكه",
    vegetables: "خضار",
    equipment: "آليات ومعدات",
    produce: "الخضر والفواكه",
    machinery: "آليات",
    livestock: "مواشي",
    fertilizers: "أسمدة",
    seeds: "بذور",
    animal_feed: "أعلاف",
    seeds_plants: "بذور ونباتات",
  },
  mocks: {
    tractorTitle: "جرار للبيع",
    tractorDesc:
      "جرار في حالة ممتازة، موديل 2018، استعمل فقط في الأعمال الخفيفة. المحرك قوي واقتصادي في استهلاك الوقود. العجلات في حالة جيدة جدا. للمزيد من المعلومات يرجى التواصل عبر الواتساب أو الإتصال المباشر.",
    sheepTitle: "خروف صردي ممتاز للعيد",
    headUnit: "رأس",
    berkane: "بركان",
    settat: "سطات",
  },
  notifications: {
    title: "الإشعارات",
    markAllRead: "تحديد الكل كمقروء",
    emptyTitle: "لا توجد إشعارات بعد",
    emptyDesc: "عندما تتلقى تحديثات، ستظهر هنا.",
    deleteTitle: "حذف الإشعار",
    deleteConfirm: "هل أنت متأكد من أنك تريد إزالة هذا الإشعار؟",
    deleteAction: "حذف",
  },
  version: {
    maintenanceTitle: "التطبيق تحت الصيانة",
    maintenanceMessage: "نقوم حالياً بإجراء صيانة دورية لتحسين خدماتنا. يرجى إعادة المحاولة لاحقاً.",
    forceUpdateTitle: "تحديث إجباري مطلوب",
    forceUpdateMessage: "يتوفر إصدار جديد من سوق الفلاح. يجب تحديث التطبيق للمتابعة.",
    optionalUpdateTitle: "تحديث جديد متوفر",
    optionalUpdateMessage: "يتوفر إصدار جديد من سوق الفلاح. هل ترغب في التحديث الآن؟",
    updateNow: "تحديث الآن",
    later: "لاحقاً",
    releaseNotes: "ما الجديد في هذا الإصدار:",
    currentVersion: "الإصدار الحالي",
    latestVersion: "الإصدار الجديد",
  },
  legal: {
    title: "الشروط والأحكام القانونية",
    cguTab: "شروط الاستخدام",
    cgvTab: "شروط البيع",
    privacyTab: "الخصوصية",
    mentionsTab: "إشعارات قانونية",
    lastUpdated: "آخر تحديث:",
    registerAcceptancePrefix: "بتسجيلك، فإنك توافق على ",
    termsLink: "شروط الاستخدام (CGU)",
    and: " و ",
    privacyLink: "سياسة الخصوصية",
    termsAndPrivacy: "الشروط والخصوصية",
    legalNotice: "الإشعارات القانونية",
  },
  forgotPassword: {
    title: "نسيت كلمة السر؟",
    subtitle: "أدخل رقم هاتفك للتواصل معنا مباشرة عبر الواتساب لإعادة تعيين كلمة السر الخاصة بك.",
    phonePlaceholder: "06 XX XX XX XX",
    whatsappBtn: "إعادة التعيين عبر الواتساب",
    callBtn: "أو الإتصال المباشر بالدعم",
    supportNote: "سيتولى فريق الدعم التثبت من حسابك ومساعدتك في اختيار كلمة سر جديدة.",
    deleteAccountTitle: "حذف حسابي",
    deleteAccountConfirm: "هل أنت متأكد من رغبتك في حذف حسابك نهائياً؟ سيتم إلغاء كافة إعلاناتك ومعلوماتك. لا يمكن التراجع عن هذا الإجراء.",
    deleteAccountSuccess: "تم حذف الحساب بنجاح.",
  },
  network: {
    noConnection: "لا يوجد اتصال بالإنترنت",
    noConnectionDesc: "يرجى التحقق من اتصالك بالشبكة وإعادة المحاولة",
    restored: "تم استعادة الاتصال بالإنترنت",
  },
}

export default ar
