import { Translations } from "./en"

const ary: Translations = {
  common: {
    ok: "موافق",
    cancel: "إلغاء",
    back: "رجوع",
    save: "حفظ",
    delete: "مسح",
    loading: "تحميل...",
    error: "خطأ",
    retry: "نعاودو",
    search: "بحث",
    call: "إتصال",
    whatsapp: "واتساب",
    location: "بلاصة",
    negotiable: "قابل للتفاوض",
    fixed: "ثمن ثابت",
    active: "نشطة",
    paused: "متوقفة",
    sold: "مباعة",
    edit: "تعديل",
    next: "التالي",
    confirm: "تأكيد",
    favorites: "المفضلة",
    currency: "درهم",
    new: "جديد",
    all: "الكل",
    farmer: "فلاح",
    seller: "البائع",
    whatsappMessage: "السلام عليكم، بغيت نسول على الإعلان ديالك: ",
    verificationFailed: "الرمز اللي دخلتي ماشي هو هاداك",
    incompleteCode: "عافاك دخل الرمز فيه 6 د الأرقام",
    warning: "تنبيه",
    notSpecified: "غير محدد",
    noFavorites: "ما عندك حتى شي إعلان فالمفضلة",
    noFavoritesDesc: "تصفح الإعلانات وكليك على القلب باش تضيف المنتوجات هنا.",
    today: "اليوم",
    yesterday: "البارح",
    daysAgo: "أيام مضت",
    days: "أيام",
    views: "مشاهدة",
    hoursUnit: "ساعة",
    noResults: "ما لقينا حتى نتيجة",
  },
  welcome: {
    title: "مرحبا بك في سوق الفلاح",
    subtitle: "سجل معانا باش تبدا تبيع وتشري المنتوجات ديالك بكل سهولة.",
    getStarted: "بدء الاستخدام",
    login: "تسجيل الدخول",
  },
  login: {
    title: "تسجيل الدخول",
    phone: "رقم الهاتف",
    phonePlaceholder: "06 XX XX XX XX",
    password: "كلمة السر",
    passwordPlaceholder: "••••••••",
    forgotPassword: "نسيتي كلمة السر؟",
    submit: "تسجيل الدخول",
    noAccount: "ما عندكش حساب؟",
    registerNow: "تسجل دابا",
    phoneRequired: "رقم التيليفون ضروري",
    phoneInvalid: "رقم التيليفون ماشي هو هاداك",
    passwordRequired: "كلمة السر ضرورية",
    passwordMinLength: "كلمة السر خاص يكون فيها على الأقل 6 د الحروف",
    loginFailedTitle: "وقع مشكل فالتسجيل",
    loginFailedMsg: "رقم التيليفون ولا كلمة السر ما صحيحاش",
  },
  register: {
    title: "فتح حساب جديد",
    fullName: "الاسم الكامل",
    fullNamePlaceholder: "مثال: أحمد العلمي",
    phone: "رقم الهاتف",
    phonePlaceholder: "06XXXXXXXX",
    password: "كلمة السر",
    passwordPlaceholder: "••••••••",
    submit: "فتح حساب جديد",
    hasAccount: "عندك حساب ديجا؟",
    loginNow: "سجل الدخول",
    nameRequired: "السمية الكاملة ضرورية",
    addressRequired: "العنوان ضروري باش نحددو بلاصة السلعة",
    registerFailedTitle: "فشل التسجيل",
    registerFailedMsg: "حدث خطأ أثناء فتح الحساب",
  },
  verifyPhone: {
    title: "تأكيد رقم الهاتف",
    subtitle: "دخل الكود اللي صيفطنا ليك فميساج (SMS) للرقم",
    submit: "تأكيد",
    resend: "ما وصلك والو؟ عاود صيفط الكود",
  },
  home: {
    title: "سوق الفلاح",
    searchPlaceholder: "قلب على منتوج...",
    categoriesTitle: "أش كتقلب؟",
    recentTitle: "آخر الإعلانات",
    viewAll: "شوف الكل",
    categories: {
      produce: "الخضر والفواكه",
      machinery: "آليات",
      livestock: "مواشي",
      fertilizers: "أسمدة",
      seeds: "بذور",
    },
  },
  search: {
    title: "البحث",
    inputPlaceholder: "شنو كتقلب عليه؟ (مثلا: تراكتور، مطيشة)",
    selectCity: "إختيار المدينة",
    categoriesSection: "الأصناف",
    allCategories: "الكل",
    priceRange: "الثمن (درهم)",
    priceFrom: "من",
    priceTo: "إلى",
    resultsCount: "نتائج البحث",
    sortBy: "ترتيب",
  },
  addListing: {
    title: "إضافة إعلان جديد",
    step1Title: "شنو بغيتي تبيع؟",
    produceCategory: "منتوجات فلاحية",
    equipmentCategory: "آليات ومعدات",
    step2Title: "ضيف صور",
    photoLimit: "بحد أقصى 5 صور",
    uploadPlaceholder: "اضغط هنا باش تختار الصور",
    listingTitleLabel: "عنوان الإعلان",
    listingTitlePlaceholder: "مثلاً: بصلة ممتازة للبيع أو تراكتور في حالة جيدة",
    listingTitleHelper: "العنوان كيعاون الناس يلقاو الإعلان ديالك بسرعة",
    priceLabel: "الثمن (درهم)",
    pricePlaceholder: "0.00",
    quantityLabel: "الكمية",
    quantityPlaceholder: "مثلاً: 100",
    unitLabel: "وحدة القياس",
    addressLabel: "العنوان",
    addressPlaceholder: "مثال: سيدي بنور، الدكالة",
    listingDirectionLabel: "نوع الإعلان",
    directionSell: "عرض بيع",
    directionBuy: "طلب شراء",
    listingPurposeLabel: "غرض الإعلان",
    purposeSell: "بيع",
    purposeRent: "كراء",
    priceTypeLabel: "نوع الثمن",
    priceTypeFixed: "ثمن ثابت",
    priceTypeNegotiable: "ثمن قابل للتفاوض",
    priceTypeContact: "الاتصال للاتفاق",
    conditionLabel: "حالة الآليات",
    conditionNew: "جديد",
    conditionUsed: "مستعمل",
    titleRequired: "العنوان ديال الإعلان ضروري",
    priceRequired: "الثمن ضروري",
    quantityRequired: "الكمية ضرورية",
    addressRequired: "العنوان ضروري",
    descriptionMinLength: "الوصف خاص يكون فيه على الأقل 10 د الحروف",
    photoLimitErrorTitle: "الحد الأقصى د الصور",
    photoLimitErrorMsg: "تقدر تضيف 5 د الصور كاع ما تفوتهاش",
    permissionDeniedTitle: "إذن مرفوض",
    permissionDeniedMsg: "خاصك تعطينا الإذن للصور باش تختار التصويرة ديالك.",
    cameraPermissionDeniedTitle: "إذن الكاميرا مرفوض",
    cameraPermissionDeniedMsg: "خاصك تعطينا الإذن للكاميرا باش تصور السلعة ديالك.",
    addPhotoSourceTitle: "زيد تصويرة",
    cameraOption: "صور بالكاميرا",
    galleryOption: "ختار من الصور",
    cancelOption: "إلغاء",
    uploadErrorTitle: "فشل رفع الصورة",
    uploadErrorMsg: "وقع مشكل فاش كنا كنحملو التصويرة.",
    missingInfoTitle: "معلومات ناقصة",
    missingInfoMsg: "عافاك عمر كاع البلايص اللي ضرورية",
    descriptionShortTitle: "الوصف قصير بزاف",
    descriptionShortMsg: "الوصف خاص يكون فيه على الأقل 10 د الحروف",
    noDescription: "ما كاينش وصف دابا",
    successTitle: "تم بنجاح",
    successMsg: "نشرنا الإعلان ديالك بنجاح على سوق الفلاح",
    successOk: "موافق",
    publishErrorTitle: "فشل نشر الإعلان",
    publishErrorDefault: "وقع مشكل فاش كنا كنحطو الإعلان",
    descriptionPlaceholder: "وصف حالة السلعة، الجودة، الموديل، إلخ.",
    descriptionLabel: "معلومات إضافية",
    modelPlaceholder: "مثال: 2018",
    modelLabel: "الموديل (السنة)",
    hoursPlaceholder: "مثال: 1200",
    hoursLabel: "عدد الساعات",
    regionLabel: "الجهة",
    selectRegionPlaceholder: "اختر الجهة",
    regionWarningTitle: "تنبيه",
    regionWarningMsg: "عافاك اختر الجهة أولاً",
    provinceLabel: "الإقليم",
    selectProvincePlaceholder: "اختر الإقليم",
    submit: "نشر الإعلان",
    categoryRequired: "القسم مطلوب",
    productTypeRequired: "نوع المنتج مطلوب",
    unitRequired: "وحدة القياس مطلوبة",
    selectCategoryPlaceholder: "اختر القسم",
    selectProductTypePlaceholder: "اختر نوع المنتج",
    selectUnitPlaceholder: "اختر وحدة القياس",
  },
  editListing: {
    title: "تعديل الإعلان",
    saveBtn: "حفظ التغييرات",
  },
  myListings: {
    title: "إعلاناتي",
    stats: {
      total: "المجموع",
      views: "المشاهدات",
      messages: "الرسائل",
    },
    tabs: {
      active: "نشطة",
      paused: "متوقفة",
      sold: "مباعة",
    },
    noListings: "ما عندك حتى شي إعلان فهاد القسم.",
    logoutTitle: "تسجيل الخروج",
    logoutConfirm: "واش متأكد بغيتي تخرج من الحساب؟",
    logoutAction: "خروج",
    deleteTitle: "حذف الإعلان",
    deleteNotSupported: "الحذف غير مدعوم حالياً فالسيرفر.",
    markSoldSuccess: "بصحتك! تم تغيير حالة الإعلان إلى مباع.",
    updateSuccess: "تم تحديث الإعلان ديالك بنجاح!",
  },
  listingDetails: {
    title: "تفاصيل الإعلان",
    memberSince: "عضو منذ",
    productInfo: "معلومات على المنتوج",
    specs: {
      model: "الموديل",
      hours: "ساعات العمل",
      quantity: "الكمية المتوفرة",
      unit: "الوحدة",
    },
    report: {
      title: "تبليغ على الإعلان",
      button: "بلغ على هاد الإعلان",
      reasonLabel: "سبب التبليغ",
      descriptionPlaceholder: "زيد شي تفاصيل أخرى (اختياري)...",
      submit: "صيفط التبليغ",
      cancel: "إلغاء",
      successTitle: "تم صيفط التبليغ",
      successMsg: "شكراً لك. وصلنا التبليغ ديالك وغادي نراجعوا هاد الإعلان قريب.",
      errorTitle: "خطأ",
      errorMsg: "ما قدرناش نصيفطوا التبليغ. عاود حاول من بعد.",
      reasons: {
        scam: "احتيال ولا نصب",
        spam: "معاود ولا ما صالحش",
        incorrect: "معلومات ولا ثمن غلاط",
        offensive: "محتوى ما كايليقش ولا مسيء",
        other: "سبب آخر",
      },
    },
  },
  guest: {
    continueAsGuest: "الاستمرار كزائر",
    loginRegisterCta: "تسجيل الدخول / إنشاء حساب",
    addListingTitle: "سجل الدخول لإضافة إعلان",
    addListingDesc:
      "باش تقدر تضيف الإعلانات والمنتجات ديالك وتواصل مع الفلاحين الآخرين، خاصك تسجل الدخول أولاً.",
    favoritesTitle: "سجل الدخول لعرض المفضلة",
    favoritesDesc:
      "باش تقدر تحفظ الإعلانات والمنتجات المفضلة عندك وترجع ليها وقتما بغيتي، خاصك تسجل الدخول.",
    myListingsTitle: "سجل الدخول لعرض حسابك",
    myListingsDesc:
      "باش تقدر تشوف الإعلانات ديالك، والمشاهدات، وتعدل الحساب ديالك، خاصك تسجل الدخول.",
    contactAlertTitle: "تنبيه",
    contactAlertMsg: "هاد الإجراء كيتطلب تسجيل الدخول. واش بغيتي تسجل الدخول أو تفتح حساب دابا؟",
    loginCta: "تسجيل الدخول",
  },
  categories: {
    fruits: "فواكه",
    vegetables: "خضرة",
    equipment: "آليات ومعدات",
    produce: "الخضر والفواكه",
    machinery: "آليات",
    livestock: "كسايب ومواشي",
    fertilizers: "أسمدة ودوا",
    seeds: "زريعة وبذور",
    animal_feed: "علف",
    seeds_plants: "زريعة ونباتات",
  },
  mocks: {
    tractorTitle: "تراكتور للبيع",
    tractorDesc:
      "تراكتور في حالة ممتازة، موديل 2018، استعمل غير في الخدمة الخفيفة. الموتور صحيح وكيقصد فالمازوط. الروايض فالعجلة مزيانين بزاف. للمزيد من المعلومات تواصل معانا فالواتساب ولا عيط لينا ديريكت.",
    sheepTitle: "صردي ممتاز للعيد",
    headUnit: "راس",
    berkane: "بركان",
    settat: "سطات",
  },
  notifications: {
    title: "الإشعارات",
    markAllRead: "علم على كولشي مقري",
    emptyTitle: "ما كاين حتى إشعار دابا",
    emptyDesc: "ملي يوصلوك إشعارات جديدة، غادي تبان هنا.",
    deleteTitle: "مسح الإشعار",
    deleteConfirm: "واش متأكد بغيتي تمسح هاد الإشعار؟",
    deleteAction: "مسح",
  },
  version: {
    maintenanceTitle: "التطبيق في الصيانة",
    maintenanceMessage: "كانديرو صيانة للتطبيق باش نصلحو ونحسنو الخدمات. عاود جرب من بعد عفاك.",
    forceUpdateTitle: "تحديث ضروري خاصك تديرو",
    forceUpdateMessage: "كاين إصدار جديد ديال سوق الفلاح. خاصك تحدّث التطبيق باش تكمل.",
    optionalUpdateTitle: "كاين تحديث جديد",
    optionalUpdateMessage: "كاين إصدار جديد ديال سوق الفلاح. واش بغيتي تحدّث دابا؟",
    updateNow: "تحديث دابا",
    later: "من بعد",
    releaseNotes: "شنو جديد ف هاد الإصدار:",
    currentVersion: "الإصدار الحالي",
    latestVersion: "الإصدار الجديد",
  },
  legal: {
    title: "الشروط والأحكام",
    cguTab: "شروط الاستعمال",
    cgvTab: "شروط البيع",
    privacyTab: "الخصوصية",
    mentionsTab: "معلومات قانونية",
    lastUpdated: "آخر تحديث:",
    registerAcceptancePrefix: "فاش كتقاد حساب جديد، راك موافق على ",
    termsLink: "شروط الاستعمال (CGU)",

    and: " و ",
    privacyLink: "سياسة الخصوصية",
    termsAndPrivacy: "الشروط والخصوصية",
    legalNotice: "المعلومات القانونية",
  },
  forgotPassword: {
    title: "نسيتي المودباس؟",
    subtitle: "دخل نمرة د تليفون ديالك باش نتواصلو معاك ف الواتساب ونبدلو ليك المودباس.",
    phonePlaceholder: "06 XX XX XX XX",
    whatsappBtn: "تواصل معانا فالواتساب",
    callBtn: "ولا عيط لينا ديريكت",
    supportNote: "غادي نتأكدو من الحساب ديالك ونساعدوك تختار مودباس جديد بكل سهولة.",
    deleteAccountTitle: "مسح الحساب ديالي",
    deleteAccountConfirm: "واش متأكد بغيتي تمسح الحساب ديالك نهائياً؟ الإعلانات والمعلومات ديالك كاملين غادي يتمسحو. هاد العملية مايمكنش ترجع فيها.",
    deleteAccountSuccess: "تم مسح الحساب بنجاح.",
  },
  network: {
    noConnection: "ماكاينش الاتصال بالأنترنيت",
    noConnectionDesc: "تأكد من الريزو والويفي ديالك وعاود حاول",
    restored: "ترجع الاتصال بالأنترنيت بنجاح",
  },
}

export default ary
