const en = {
  common: {
    ok: "OK",
    cancel: "Cancel",
    back: "Back",
    save: "Save",
    delete: "Delete",
    loading: "Loading...",
    error: "Error",
    retry: "Retry",
    search: "Search",
    call: "Call",
    whatsapp: "WhatsApp",
    location: "Location",
    negotiable: "Negotiable",
    fixed: "Fixed Price",
    active: "Active",
    paused: "Paused",
    sold: "Sold",
    edit: "Edit",
    next: "Next",
    confirm: "Confirm",
    favorites: "Favorites",
    currency: "DH",
    new: "New",
    all: "All",
    farmer: "Farmer",
    seller: "Seller",
    whatsappMessage: "Hello, I want to ask about your listing: ",
    verificationFailed: "Verification code is incorrect.",
    incompleteCode: "Please enter the 6-digit code.",
    warning: "Warning",
    notSpecified: "Not Specified",
    noFavorites: "No favorites yet",
    noFavoritesDesc: "Browse listings and tap the heart icon to save products here.",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo: "days ago",
    days: "days",
    views: "views",
    hoursUnit: "hours",
    noResults: "No results found",
  },
  welcome: {
    title: "Welcome to Souk El Fellah",
    subtitle: "Register with us to buy and sell your agricultural products easily.",
    getStarted: "Get Started",
    login: "Log In",
  },
  login: {
    title: "Log In",
    phone: "Phone Number",
    phonePlaceholder: "06 XX XX XX XX",
    password: "Password",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Forgot Password?",
    submit: "Log In",
    noAccount: "Don't have an account?",
    registerNow: "Register now",
    phoneRequired: "Phone number is required",
    phoneInvalid: "Invalid phone number",
    passwordRequired: "Password is required",
    passwordMinLength: "Password must be at least 6 characters",
    loginFailedTitle: "Login Failed",
    loginFailedMsg: "Incorrect phone number or password",
  },
  register: {
    title: "Create New Account",
    fullName: "Full Name",
    fullNamePlaceholder: "Example: Ahmed Alami",
    phone: "Phone Number",
    phonePlaceholder: "06XXXXXXXX",
    password: "Password",
    passwordPlaceholder: "••••••••",
    submit: "Register",
    hasAccount: "Already have an account?",
    loginNow: "Log in",
    nameRequired: "Full name is required",
    addressRequired: "Address is required to locate listings",
    registerFailedTitle: "Registration Failed",
    registerFailedMsg: "An error occurred during registration",
  },
  verifyPhone: {
    title: "Verify Phone Number",
    subtitle: "Enter the code we sent in an SMS to number",
    submit: "Confirm",
    resend: "Didn't receive anything? Resend code",
  },
  home: {
    title: "Souk El Fellah",
    searchPlaceholder: "Search for a product...",
    categoriesTitle: "What are you looking for?",
    recentTitle: "Recent Listings",
    viewAll: "View All",
    categories: {
      produce: "Fruits & Vegetables",
      machinery: "Machinery",
      livestock: "Livestock",
      fertilizers: "Fertilizers",
      seeds: "Seeds",
    },
  },
  search: {
    title: "Search",
    inputPlaceholder: "What are you looking for? (e.g. tractor, tomatoes)",
    selectCity: "Select Location",
    categoriesSection: "Categories",
    allCategories: "All",
    priceRange: "Price (MAD)",
    priceFrom: "From",
    priceTo: "To",
    resultsCount: "Search Results",
    sortBy: "Sort By",
  },
  addListing: {
    title: "Add New Listing",
    step1Title: "What do you want to sell?",
    produceCategory: "Agricultural Products",
    equipmentCategory: "Machinery & Equipment",
    step2Title: "Add Photos",
    photoLimit: "Maximum 5 photos",
    uploadPlaceholder: "Tap here to choose photos",
    listingTitleLabel: "Listing Title",
    listingTitlePlaceholder: "e.g. Excellent tomatoes for sale or tractor in good condition",
    listingTitleHelper: "Titles help buyers find your listing quickly",
    priceLabel: "Price (MAD)",
    pricePlaceholder: "0.00",
    quantityLabel: "Quantity",
    quantityPlaceholder: "e.g. 100",
    unitLabel: "Measurement Unit",
    addressLabel: "Address",
    addressPlaceholder: "e.g. Sidi Bennour, Doukkala",
    listingDirectionLabel: "Listing Type",
    directionSell: "For Sale (Supply)",
    directionBuy: "Wanted (Demand)",
    listingPurposeLabel: "Purpose",
    purposeSell: "Sell",
    purposeRent: "Rent",
    priceTypeLabel: "Price Type",
    priceTypeFixed: "Fixed Price",
    priceTypeNegotiable: "Negotiable",
    priceTypeContact: "Contact",
    conditionLabel: "Condition",
    conditionNew: "New",
    conditionUsed: "Used",
    titleRequired: "Title is required",
    priceRequired: "Price is required",
    quantityRequired: "Quantity is required",
    addressRequired: "Address is required",
    descriptionMinLength: "Description must be at least 10 characters",
    photoLimitErrorTitle: "Photo Limit",
    photoLimitErrorMsg: "You can add a maximum of 5 photos",
    permissionDeniedTitle: "Permission Denied",
    permissionDeniedMsg: "Access to photos is required.",
    cameraPermissionDeniedTitle: "Camera Permission Denied",
    cameraPermissionDeniedMsg: "Access to the camera is required to take photos of your item.",
    addPhotoSourceTitle: "Add Photo",
    cameraOption: "Take Photo",
    galleryOption: "Choose from Gallery",
    cancelOption: "Cancel",
    uploadErrorTitle: "Upload Failed",
    uploadErrorMsg: "An error occurred during photo upload.",
    missingInfoTitle: "Missing Information",
    missingInfoMsg: "Please fill all required fields.",
    descriptionShortTitle: "Description Too Short",
    descriptionShortMsg: "Description must be at least 10 characters.",
    noDescription: "No description currently",
    successTitle: "Success",
    successMsg: "Your listing has been successfully published.",
    successOk: "OK",
    publishErrorTitle: "Publish Failed",
    publishErrorDefault: "An error occurred during publishing.",
    descriptionPlaceholder: "Describe item condition, quality, model etc.",
    descriptionLabel: "Additional Info",
    modelPlaceholder: "e.g. 2018",
    modelLabel: "Model (Year)",
    hoursPlaceholder: "e.g. 1200",
    hoursLabel: "Hours Count",
    regionLabel: "Region",
    selectRegionPlaceholder: "Select Region",
    regionWarningTitle: "Warning",
    regionWarningMsg: "Please select a region first.",
    provinceLabel: "Province",
    selectProvincePlaceholder: "Select Province",
    submit: "Publish Listing",
    categoryRequired: "Category is required",
    productTypeRequired: "Product type is required",
    unitRequired: "Measurement unit is required",
    selectCategoryPlaceholder: "Select Category",
    selectProductTypePlaceholder: "Select Product Type",
    selectUnitPlaceholder: "Select Measurement Unit",
  },
  editListing: {
    title: "Edit Listing",
    saveBtn: "Save Changes",
  },
  myListings: {
    title: "My Listings",
    stats: {
      total: "Total",
      views: "Views",
      messages: "Messages",
    },
    tabs: {
      active: "Active",
      paused: "Paused",
      sold: "Sold",
    },
    noListings: "You have no listings in this section.",
    logoutTitle: "Log Out",
    logoutConfirm: "Are you sure you want to log out?",
    logoutAction: "Log Out",
    deleteTitle: "Delete Listing",
    deleteNotSupported: "Deleting is not supported yet on the server.",
    markSoldSuccess: "Congratulations! Listing marked as sold.",
    updateSuccess: "Your listing has been updated successfully!",
  },
  listingDetails: {
    title: "Listing Details",
    memberSince: "Member since",
    productInfo: "Product Information",
    specs: {
      model: "Model",
      hours: "Working Hours",
      quantity: "Available Quantity",
      unit: "Unit",
    },
    report: {
      title: "Report Listing",
      button: "Report this listing",
      reasonLabel: "Reason for reporting",
      descriptionPlaceholder: "Provide more details (optional)...",
      submit: "Submit Report",
      cancel: "Cancel",
      successTitle: "Report Submitted",
      successMsg: "Thank you. We have received your report and will review this listing shortly.",
      errorTitle: "Error",
      errorMsg: "Could not submit report. Please try again later.",
      reasons: {
        scam: "Fraud or scam",
        spam: "Spam or duplicate",
        incorrect: "Incorrect details / price",
        offensive: "Inappropriate / offensive content",
        other: "Other reason",
      },
    },
  },
  guest: {
    continueAsGuest: "Continue as Guest",
    loginRegisterCta: "Log In / Register",
    addListingTitle: "Log In to Add a Listing",
    addListingDesc:
      "To be able to add your listings and products, and connect with other farmers, you must log in first.",
    favoritesTitle: "Log In to View Favorites",
    favoritesDesc:
      "To be able to save your favorite listings and products and return to them whenever you want, you must log in.",
    myListingsTitle: "Log In to View Your Account",
    myListingsDesc:
      "To be able to see your listings, views, and manage your account, you must log in first.",
    contactAlertTitle: "Notice",
    contactAlertMsg:
      "This action requires logging in. Would you like to log in or create an account now?",
    loginCta: "Log In",
  },
  categories: {
    fruits: "Fruits",
    vegetables: "Vegetables",
    equipment: "Machinery & Equipment",
    produce: "Produce",
    machinery: "Machinery",
    livestock: "Livestock",
    fertilizers: "Fertilizers",
    seeds: "Seeds",
    animal_feed: "Animal Feed",
    seeds_plants: "Seeds & Plants",
  },
  mocks: {
    tractorTitle: "Tractor for sale",
    tractorDesc: "Tractor in excellent condition, 2018 model, used only for light work...",
    sheepTitle: "Excellent Sardi Sheep for Eid",
    headUnit: "head",
    berkane: "Berkane",
    settat: "Settat",
  },
  notifications: {
    title: "Notifications",
    markAllRead: "Mark all as read",
    emptyTitle: "No notifications yet",
    emptyDesc: "When you receive updates, they'll show up here.",
    deleteTitle: "Delete Notification",
    deleteConfirm: "Are you sure you want to remove this notification?",
    deleteAction: "Delete",
  },
  version: {
    maintenanceTitle: "App Under Maintenance",
    maintenanceMessage: "We are currently performing scheduled maintenance to improve our services. Please check back soon.",
    forceUpdateTitle: "Mandatory Update Required",
    forceUpdateMessage: "A new version of Souk El Fellah is available. You must update the app to continue using it.",
    optionalUpdateTitle: "New Update Available",
    optionalUpdateMessage: "A new version of Souk El Fellah is available. Would you like to update now?",
    updateNow: "Update Now",
    later: "Later",
    releaseNotes: "What's New:",
    currentVersion: "Current Version",
    latestVersion: "New Version",
  },
  legal: {
    title: "Terms & Legal Notices",
    cguTab: "CGU",
    cgvTab: "CGV",
    privacyTab: "Privacy Policy",
    mentionsTab: "Legal Notice",
    lastUpdated: "Last updated:",
    registerAcceptancePrefix: "By registering, you accept our ",
    termsLink: "Terms of Use (CGU)",
    and: " and ",
    privacyLink: "Privacy Policy",
    termsAndPrivacy: "Terms & Privacy",
    legalNotice: "Legal Notices",
  },
  forgotPassword: {
    title: "Forgot Password?",
    subtitle: "Enter your phone number to contact our support on WhatsApp and reset your password.",
    phonePlaceholder: "06 XX XX XX XX",
    whatsappBtn: "Reset via WhatsApp",
    callBtn: "Or Call Support Directly",
    supportNote: "Our team will verify your account and assist you in setting a new password.",
    deleteAccountTitle: "Delete My Account",
    deleteAccountConfirm: "Are you sure you want to delete your account permanently? All your active listings and data will be removed. This action cannot be undone.",
    deleteAccountSuccess: "Account deleted successfully.",
  },
  network: {
    noConnection: "No Internet Connection",
    noConnectionDesc: "Please check your network settings and try again",
    restored: "Internet Connection Restored",
  },
}


export default en


export type Translations = typeof en
