import { Translations } from "./en"

const fr: Translations = {
  common: {
    ok: "OK",
    cancel: "Annuler",
    back: "Retour",
    save: "Enregistrer",
    delete: "Supprimer",
    loading: "Chargement...",
    error: "Erreur",
    retry: "Réessayer",
    search: "Rechercher",
    call: "Appeler",
    whatsapp: "WhatsApp",
    location: "Localisation",
    negotiable: "Négociable",
    fixed: "Prix fixe",
    active: "Actif",
    paused: "En pause",
    sold: "Vendu",
    edit: "Modifier",
    next: "Suivant",
    confirm: "Confirmer",
    favorites: "Favoris",
    currency: "DH",
    new: "Nouveau",
    all: "Tout",
    farmer: "Agriculteur",
    seller: "Vendeur",
    whatsappMessage: "Bonjour, je souhaite me renseigner sur votre annonce : ",
    verificationFailed: "Le code de vérification est incorrect.",
    incompleteCode: "Veuillez saisir le code à 6 chiffres.",
    warning: "Avertissement",
    notSpecified: "Non spécifié",
    noFavorites: "Aucun favori pour le moment",
    noFavoritesDesc:
      "Explorez les annonces et cliquez sur le cœur pour enregistrer vos produits ici.",
    today: "Aujourd'hui",
    daysAgo: "jours",
    days: "jours",
    views: "vues",
    hoursUnit: "heures",
  },
  welcome: {
    title: "Bienvenue sur Souk El Fellah",
    subtitle: "Inscrivez-vous pour acheter et vendre vos produits agricoles facilement.",
    getStarted: "Commencer",
    login: "Se connecter",
  },
  login: {
    title: "Connexion",
    phone: "Numéro de téléphone",
    phonePlaceholder: "06 XX XX XX XX",
    password: "Mot de passe",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Mot de passe oublié ?",
    submit: "Se connecter",
    noAccount: "Vous n'avez pas de compte ?",
    registerNow: "S'inscrire maintenant",
    phoneRequired: "Numéro de téléphone requis",
    phoneInvalid: "Numéro de téléphone invalide",
    passwordRequired: "Mot de passe requis",
    passwordMinLength: "Le mot de passe doit comporter au moins 6 caractères",
    loginFailedTitle: "Échec de la connexion",
    loginFailedMsg: "Numéro de téléphone ou mot de passe incorrect",
  },
  register: {
    title: "Créer un compte",
    fullName: "Nom complet",
    fullNamePlaceholder: "Ex: Ahmed Alami",
    phone: "Numéro de téléphone",
    phonePlaceholder: "06XXXXXXXX",
    password: "Mot de passe",
    passwordPlaceholder: "••••••••",
    submit: "S'inscrire",
    hasAccount: "Vous avez déjà un compte ?",
    loginNow: "Se connecter",
    nameRequired: "Nom complet requis",
    addressRequired: "L'adresse est requise pour localiser les annonces",
    registerFailedTitle: "Échec de l'inscription",
    registerFailedMsg: "Une erreur est survenue lors de la création du compte",
  },
  verifyPhone: {
    title: "Vérifier le téléphone",
    subtitle: "Entrez le code envoyé par SMS au numéro",
    submit: "Confirmer",
    resend: "Rien reçu ? Renvoyer le code",
  },
  home: {
    title: "Souk El Fellah",
    searchPlaceholder: "Rechercher un produit...",
    categoriesTitle: "Que recherchez-vous ?",
    recentTitle: "Annonces Récentes",
    viewAll: "Voir Tout",
    categories: {
      produce: "Fruits & Légumes",
      machinery: "Matériel",
      livestock: "Bétail",
      fertilizers: "Engrais",
      seeds: "Semences",
    },
  },
  search: {
    title: "Recherche",
    inputPlaceholder: "Que recherchez-vous ? (ex: tracteur, tomates)",
    selectCity: "Choisir la ville",
    categoriesSection: "Catégories",
    allCategories: "Tout",
    priceRange: "Prix (DH)",
    priceFrom: "De",
    priceTo: "À",
    resultsCount: "Résultats de recherche",
    sortBy: "Trier par",
  },
  addListing: {
    title: "Nouvelle Annonce",
    step1Title: "Que voulez-vous vendre ?",
    produceCategory: "Produits Agricoles",
    equipmentCategory: "Matériel & Équipement",
    step2Title: "Ajouter des photos",
    photoLimit: "Maximum 5 photos",
    uploadPlaceholder: "Appuyez ici pour choisir les photos",
    listingTitleLabel: "Titre de l'annonce",
    listingTitlePlaceholder: "Ex: Excellentes tomates à vendre ou tracteur en bon état",
    listingTitleHelper: "Le titre aide les acheteurs à trouver votre annonce rapidement",
    priceLabel: "Prix (DH)",
    pricePlaceholder: "0.00",
    quantityLabel: "Quantité",
    quantityPlaceholder: "Ex: 100",
    unitLabel: "Unité de mesure",
    addressLabel: "Adresse",
    addressPlaceholder: "Ex: Sidi Bennour, Doukkala",
    listingDirectionLabel: "Type d'annonce",
    directionSell: "À Vendre",
    directionBuy: "Je cherche",
    listingPurposeLabel: "Objectif",
    purposeSell: "Vente",
    purposeRent: "Location",
    priceTypeLabel: "Type de prix",
    priceTypeFixed: "Prix Fixe",
    priceTypeNegotiable: "Négociable",
    priceTypeContact: "Contact",
    conditionLabel: "État",
    conditionNew: "Neuf",
    conditionUsed: "Occasion",
    titleRequired: "Le titre de l'annonce est requis",
    priceRequired: "Le prix est requis",
    quantityRequired: "La quantité est requise",
    addressRequired: "L'adresse est requise",
    descriptionMinLength: "La description doit contenir au moins 10 caractères",
    photoLimitErrorTitle: "Limite de Photos",
    photoLimitErrorMsg: "Vous pouvez ajouter un maximum de 5 photos.",
    permissionDeniedTitle: "Permission Refusée",
    permissionDeniedMsg: "L'accès aux photos est requis pour choisir une image.",
    cameraPermissionDeniedTitle: "Permission caméra refusée",
    cameraPermissionDeniedMsg: "L'accès à l'appareil photo est requis pour prendre des photos de vos articles.",
    addPhotoSourceTitle: "Ajouter une photo",
    cameraOption: "Prendre une photo",
    galleryOption: "Choisir depuis la galerie",
    cancelOption: "Annuler",
    uploadErrorTitle: "Échec du Téléchargement",
    uploadErrorMsg: "Une erreur est survenue lors de l'envoi de la photo.",
    missingInfoTitle: "Informations Manquantes",
    missingInfoMsg: "Veuillez remplir tous les champs requis.",
    descriptionShortTitle: "Description trop courte",
    descriptionShortMsg: "La description doit contenir au moins 10 caractères.",
    noDescription: "Aucune description",
    successTitle: "Succès",
    successMsg: "Votre annonce a été publiée avec succès sur Souk El Fellah.",
    successOk: "OK",
    publishErrorTitle: "Échec de publication",
    publishErrorDefault: "Une erreur est survenue lors de la publication.",
    descriptionPlaceholder: "Décrivez l'état, qualité, modèle etc.",
    descriptionLabel: "Informations Complémentaires",
    modelPlaceholder: "Ex: 2018",
    modelLabel: "Modèle (Année)",
    hoursPlaceholder: "Ex: 1200",
    hoursLabel: "Nombre d'heures",
    regionLabel: "Région",
    selectRegionPlaceholder: "Choisir la Région",
    regionWarningTitle: "Avertissement",
    regionWarningMsg: "Veuillez d'abord choisir une région.",
    provinceLabel: "Province",
    selectProvincePlaceholder: "Choisir la Province",
    submit: "Publier l'annonce",
    categoryRequired: "La catégorie est obligatoire",
    productTypeRequired: "Le type de produit est obligatoire",
    unitRequired: "L'unité de mesure est obligatoire",
    selectCategoryPlaceholder: "Choisir la Catégorie",
    selectProductTypePlaceholder: "Choisir le Type de Produit",
    selectUnitPlaceholder: "Choisir l'Unité de Mesure",
  },
  myListings: {
    title: "Mes Annonces",
    stats: {
      total: "Total",
      views: "Vues",
      messages: "Messages",
    },
    tabs: {
      active: "Actif",
      paused: "En pause",
      sold: "Vendu",
    },
    noListings: "Vous n'avez aucune annonce dans cette section.",
    logoutTitle: "Déconnexion",
    logoutConfirm: "Êtes-vous sûr de vouloir vous déconnecter ?",
    logoutAction: "Se déconnecter",
    deleteTitle: "Supprimer l'annonce",
    deleteNotSupported: "La suppression n'est pas encore supportée par le serveur.",
    markSoldSuccess: "Félicitations! L'annonce a été marquée comme vendue.",
  },
  listingDetails: {
    title: "Détails de l'annonce",
    memberSince: "Membre depuis",
    productInfo: "Informations sur le produit",
    specs: {
      model: "Modèle",
      hours: "Heures de travail",
      quantity: "Quantité disponible",
      unit: "Unité",
    },
    report: {
      title: "Signaler l'annonce",
      button: "Signaler cette annonce",
      reasonLabel: "Raison du signalement",
      descriptionPlaceholder: "Fournir plus de détails (optionnel)...",
      submit: "Envoyer le signalement",
      cancel: "Annuler",
      successTitle: "Signalement envoyé",
      successMsg: "Merci. Nous avons reçu votre signalement et examinerons cette annonce sous peu.",
      errorTitle: "Erreur",
      errorMsg: "Impossible d'envoyer le signalement. Veuillez réessayer plus tard.",
      reasons: {
        scam: "Fraude ou escroquerie",
        spam: "Spam ou doublon",
        incorrect: "Détails / prix incorrects",
        offensive: "Contenu inapproprié / offensant",
        other: "Autre raison",
      },
    },
  },
  guest: {
    continueAsGuest: "Continuer en tant qu'invité",
    loginRegisterCta: "Se connecter / S'inscrire",
    addListingTitle: "Connectez-vous pour ajouter une annonce",
    addListingDesc:
      "Pour pouvoir ajouter vos annonces et produits, et vous connecter avec d'autres agriculteurs, vous devez d'abord vous connecter.",
    favoritesTitle: "Connectez-vous pour voir vos favoris",
    favoritesDesc:
      "Pour pouvoir enregistrer vos annonces et produits préférés et y revenir quand vous le souhaitez, vous devez vous connecter.",
    myListingsTitle: "Connectez-vous pour voir votre compte",
    myListingsDesc:
      "Pour pouvoir voir vos annonces, vos vues, et gérer votre compte, vous devez d'abord vous connecter.",
    contactAlertTitle: "Avis",
    contactAlertMsg:
      "Cette action nécessite de se connecter. Souhaitez-vous vous connecter ou créer un compte maintenant ?",
    loginCta: "Se connecter",
  },
  categories: {
    fruits: "Fruits",
    vegetables: "Légumes",
    equipment: "Matériel & Équipement",
    produce: "Fruits & Légumes",
    machinery: "Machines",
    livestock: "Bétail",
    fertilizers: "Engrais",
    seeds: "Semences",
    animal_feed: "Alimentation Animale",
    seeds_plants: "Graines & Plantes",
  },
  mocks: {
    tractorTitle: "Tracteur à vendre",
    tractorDesc: "Tracteur en excellent état, modèle 2018, utilisé pour travaux légers...",
    sheepTitle: "Mouton Sardi pour l'Aïd",
    headUnit: "tête",
    berkane: "Berkane",
    settat: "Settat",
  },
}

export default fr
